package com.yancy.ipfs.mapper;

import com.yancy.ipfs.pojo.Uploadfile;
import com.yancy.ipfs.pojo.UploadfileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UploadfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uploadfile
     *
     * @mbg.generated Sun Jun 10 15:33:36 CST 2018
     */
    long countByExample(UploadfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uploadfile
     *
     * @mbg.generated Sun Jun 10 15:33:36 CST 2018
     */
    int deleteByExample(UploadfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uploadfile
     *
     * @mbg.generated Sun Jun 10 15:33:36 CST 2018
     */
    int insert(Uploadfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uploadfile
     *
     * @mbg.generated Sun Jun 10 15:33:36 CST 2018
     */
    int insertSelective(Uploadfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uploadfile
     *
     * @mbg.generated Sun Jun 10 15:33:36 CST 2018
     */
    List<Uploadfile> selectByExample(UploadfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uploadfile
     *
     * @mbg.generated Sun Jun 10 15:33:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") Uploadfile record, @Param("example") UploadfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uploadfile
     *
     * @mbg.generated Sun Jun 10 15:33:36 CST 2018
     */
    int updateByExample(@Param("record") Uploadfile record, @Param("example") UploadfileExample example);
}