package com.yancy.ipfs.pojo;

import java.util.Date;

public class Uploadfile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uploadfile.fileid
     *
     * @mbg.generated Sun Jun 10 15:33:36 CST 2018
     */
    private Integer fileid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uploadfile.filename
     *
     * @mbg.generated Sun Jun 10 15:33:36 CST 2018
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uploadfile.ipfshash
     *
     * @mbg.generated Sun Jun 10 15:33:36 CST 2018
     */
    private String ipfshash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uploadfile.uploadtime
     *
     * @mbg.generated Sun Jun 10 15:33:36 CST 2018
     */
    private Date uploadtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uploadfile.fileid
     *
     * @return the value of uploadfile.fileid
     *
     * @mbg.generated Sun Jun 10 15:33:36 CST 2018
     */
    public Integer getFileid() {
        return fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uploadfile.fileid
     *
     * @param fileid the value for uploadfile.fileid
     *
     * @mbg.generated Sun Jun 10 15:33:36 CST 2018
     */
    public void setFileid(Integer fileid) {
        this.fileid = fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uploadfile.filename
     *
     * @return the value of uploadfile.filename
     *
     * @mbg.generated Sun Jun 10 15:33:36 CST 2018
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uploadfile.filename
     *
     * @param filename the value for uploadfile.filename
     *
     * @mbg.generated Sun Jun 10 15:33:36 CST 2018
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uploadfile.ipfshash
     *
     * @return the value of uploadfile.ipfshash
     *
     * @mbg.generated Sun Jun 10 15:33:36 CST 2018
     */
    public String getIpfshash() {
        return ipfshash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uploadfile.ipfshash
     *
     * @param ipfshash the value for uploadfile.ipfshash
     *
     * @mbg.generated Sun Jun 10 15:33:36 CST 2018
     */
    public void setIpfshash(String ipfshash) {
        this.ipfshash = ipfshash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uploadfile.uploadtime
     *
     * @return the value of uploadfile.uploadtime
     *
     * @mbg.generated Sun Jun 10 15:33:36 CST 2018
     */
    public Date getUploadtime() {
        return uploadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uploadfile.uploadtime
     *
     * @param uploadtime the value for uploadfile.uploadtime
     *
     * @mbg.generated Sun Jun 10 15:33:36 CST 2018
     */
    public void setUploadtime(Date uploadtime) {
        this.uploadtime = uploadtime;
    }
}